
// /*
// Holyoke Framework: library for GUI-based database applications
// This file Copyright (c) 2006-2008 by Robert Fischer
// 
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
// */
// /*
//  * DBPrefsDialog.java
//  *
//  * Created on March 11, 2006, 6:00 PM
//  */
// 
// package citibob.gui;
// 
// import java.awt.event.*;
// import java.util.prefs.*;
// import de.jppietsch.prefedit.*;
// import java.util.*;
// import citibob.swing.prefs.*;
// import java.sql.*;
// import citibob.sql.*;
// import javax.swing.*;
// 
// /**
//  *
//  * @author  citibob
//  */
// public class DBPrefsDialog extends javax.swing.JDialog
// {
// 
// DBPrefsTableModel model;
// 
// boolean okPressed;
// 
//     /** Creates new form DBPrefsDialog */
//     public DBPrefsDialog(java.awt.Frame parent, Preferences pref,
// 		SwingPrefs swingPrefs, Preferences guiPref)
// 	throws BackingStoreException {
//         super(parent, "Database Connection", true);
//         initComponents();
// 
// 
// 		model = new DBPrefsTableModel(pref);
// 		prefsTable.setModel(model);
// 
// 		// Pressing ENTER will initiate search.
// 		tfPassword.addKeyListener(new KeyAdapter() {
// 	    public void keyTyped(KeyEvent e) {
// 			//System.out.println(e.getKeyChar());
// 			if (e.getKeyChar() == '\n') doOK();
// 		}});
// 
// 		// Set focus to password box when dialog opens
// 		this.addWindowListener(new WindowAdapter() {
// 		public void windowOpened(WindowEvent e) {
// 			tfPassword.requestFocus();
// 		}});
// 
// 		// Save GUI Preferences preferences
// 		swingPrefs.setPrefs(this, guiPref);
// 
//     }
// 
// void doOK()
// {
// 	// Check that database can be opened.
// 	ConnPool cp = null;
// 	Connection c = null;
// 	try {
// 		cp = newConnPool();
// 		c = cp.checkout();
// 		okPressed = true;
// 		dispose();
// 	} catch(Exception e) {
// 		String str = "Error opening database: " + e.toString();
// 		JOptionPane.showMessageDialog(this,str);
// 	} finally {
// 		try {
// 			if (cp != null) {
// 				if (c != null) cp.checkin(c);
// 				cp.dispose();
// 			}
// 		} catch(Exception ee) {}
// 	}
// }
// 
// 
// public String getPassword()
// 	{ return tfPassword.getText(); }
// public boolean isOkPressed()
// 	{ return okPressed; }
// 
// public ConnPool newConnPool() throws SQLException, ClassNotFoundException
// {
// 	return new DBPrefsTableModel.DBConnPool(model.getPrefs(), getPassword());
// }
// 
//     /** This method is called from within the constructor to
//      * initialize the form.
//      * WARNING: Do NOT modify this code. The content of this method is
//      * always regenerated by the Form Editor.
//      */
//     // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
//     private void initComponents() {
//         jScrollPane1 = new javax.swing.JScrollPane();
//         prefsTable = new citibob.swing.CitibobJTable();
//         jPanel1 = new javax.swing.JPanel();
//         jLabel1 = new javax.swing.JLabel();
//         tfPassword = new javax.swing.JPasswordField();
//         bOK = new javax.swing.JButton();
//         bCancel = new javax.swing.JButton();
// 
//         setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
//         prefsTable.setModel(new javax.swing.table.DefaultTableModel(
//             new Object [][] {
//                 {null, null, null, null},
//                 {null, null, null, null},
//                 {null, null, null, null},
//                 {null, null, null, null}
//             },
//             new String [] {
//                 "Title 1", "Title 2", "Title 3", "Title 4"
//             }
//         ));
//         jScrollPane1.setViewportView(prefsTable);
// 
//         getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);
// 
//         jPanel1.setLayout(new java.awt.GridLayout(2, 2));
// 
//         jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
//         jLabel1.setText("Password: ");
//         jPanel1.add(jLabel1);
// 
//         jPanel1.add(tfPassword);
// 
//         bOK.setText("OK");
//         bOK.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 bOKActionPerformed(evt);
//             }
//         });
// 
//         jPanel1.add(bOK);
// 
//         bCancel.setText("Cancel");
//         bCancel.addActionListener(new java.awt.event.ActionListener() {
//             public void actionPerformed(java.awt.event.ActionEvent evt) {
//                 bCancelActionPerformed(evt);
//             }
//         });
// 
//         jPanel1.add(bCancel);
// 
//         getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);
// 
//         pack();
//     }
//     // </editor-fold>//GEN-END:initComponents
// 
// private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
// 	okPressed = false;
// 	dispose();
// }//GEN-LAST:event_bCancelActionPerformed
// 
// private void bOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOKActionPerformed
// 	doOK();
// }//GEN-LAST:event_bOKActionPerformed
// 
// //    /**
// //    * @param args the command line arguments
// //    */
// //    public static void main(String args[]) throws Exception {
// //		DBPrefsDialog d = new DBPrefsDialog(new javax.swing.JFrame(), "offstage/db", "offstage/gui/DBPrefsDialog");
// //		d.setVisible(true);
// //		System.out.println(d.getPassword());
// //    }
// 
//     // Variables declaration - do not modify//GEN-BEGIN:variables
//     private javax.swing.JButton bCancel;
//     private javax.swing.JButton bOK;
//     private javax.swing.JLabel jLabel1;
//     private javax.swing.JPanel jPanel1;
//     private javax.swing.JScrollPane jScrollPane1;
//     private citibob.swing.CitibobJTable prefsTable;
//     private javax.swing.JPasswordField tfPassword;
//     // End of variables declaration//GEN-END:variables
// 
// }
// 