/*
Holyoke Framework: library for GUI-based database applications
This file Copyright (c) 2006-2008 by Robert Fischer

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*
 * ThreadConsoleGui.java
 *
 */

package citibob.gui;

import citibob.swing.prefs.SwingPrefs;
import java.io.*;
import javax.swing.*;
import javax.swing.text.*;
import javax.swing.table.*;
import java.util.prefs.*;
import gnu.xml.dom.ls.WriterOutputStream;
import foundry.io.DocumentWriter;
import javax.swing.event.*;
import citibob.swing.text.*;
import citibob.swing.text.CircularPlainDocument;

/**
 * Offers an entire GUI console window for text-based applications.
 */
public class ThreadConsoleGui extends javax.swing.JFrame {

	
	static {
		try {
			UIManager.setLookAndFeel(
			"com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
		} catch(Exception e) {}
	}
	
	/**
	 * Creates new form ThreadConsoleGui 
	 */
	public ThreadConsoleGui() {
		initComponents();
		logText.setLineWrap(true);
		logText.setWrapStyleWord(true);
		logText.setEditable(false);
//		setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
	}
	
Thread thread;
DocumentWriter logWriter;

public void initRuntime(Thread thread, SwingPrefs swingPrefs, String title)
{
	setTitle(title);
	this.thread = thread;
	Document doc = new CircularPlainDocument(20000);
	logWriter = new DocumentWriter(doc);

	// Set up log window
	logText.setDocument(doc);
	System.setOut(new PrintStream(new WriterOutputStream(logWriter)));
	doc.addDocumentListener(new DocumentListener() {
		public void changedUpdate(DocumentEvent e) {} 
		public void removeUpdate(DocumentEvent e) {}
		public void insertUpdate(DocumentEvent e) {
			final JScrollBar sb = logScrollPane.getVerticalScrollBar();
			java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				sb.setValue(sb.getMaximum());
			}});
		}
	});
	
	
	Preferences prefs = Preferences.userNodeForPackage(thread.getClass());
	swingPrefs.setPrefs(this, prefs);
}
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        logScrollPane = new javax.swing.JScrollPane();
        logText = new javax.swing.JTextArea();
        jToolBar1 = new javax.swing.JToolBar();
        bStop = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("OmniFX Quote Server");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        logScrollPane.setViewportView(logText);

        getContentPane().add(logScrollPane, java.awt.BorderLayout.CENTER);

        bStop.setText("Stop");
        bStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStopActionPerformed(evt);
            }
        });

        jToolBar1.add(bStop);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

	private void bStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStopActionPerformed
		System.out.println("Interrupting the thread... (alive = " + thread.isAlive() + ")");
		thread.interrupt();
	}//GEN-LAST:event_bStopActionPerformed

	private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
System.err.println("formWindowClosing");
		if (thread.isAlive()) {
			String msg = "Do you really wish to stop this thread?";
			// Modal dialog with yes/no button
			int answer = JOptionPane.showOptionDialog(this, msg, "Exit FXServer?", 
				JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
				null, null);
			if (answer == JOptionPane.YES_OPTION) {
				System.out.println("Interrupting the thread...");
				thread.interrupt();
			} else if (answer == JOptionPane.NO_OPTION) {
				// User clicked NO.
			}
		} else {
			System.exit(0);
		}
	}//GEN-LAST:event_formWindowClosing

	private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

	}//GEN-LAST:event_formWindowClosed
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bStop;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JScrollPane logScrollPane;
    private javax.swing.JTextArea logText;
    // End of variables declaration//GEN-END:variables
	
}
