/*
Holyoke Framework: library for GUI-based database applications
This file Copyright (c) 2006-2008 by Robert Fischer

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*
 * AuthenticatorDialog.java
 *
 * Created on July 23, 2004, 12:08 AM
 */

package citibob.mail;


/**
 *
 * @author  citibob
 */
public class AuthenticatorDialog extends javax.swing.JDialog {

boolean okPressed;
boolean passwordChanged;

public boolean getOK() { return okPressed; }
public boolean getPasswordChanged() { return passwordChanged; }
public String getPassword() { return new String(password.getPassword()); }
public boolean getRememberPassword() { return rememberPassword.isSelected(); }

    
    /** Creates new form AuthenticatorDialog */
    public AuthenticatorDialog(java.awt.Frame parent, String host,
    String username, int passwordLen, boolean rememberPassword, String statusMessage) {
        super(parent, true);
        initComponents();
        lMessage.setText(statusMessage);
		message1.setText("Enter your password for " + username);
		message2.setText("on " + host + ":");
		char[] pwd = new char[passwordLen];
		for (int i = 0; i < passwordLen; ++i) pwd[i]='*';
		password.setText(new String(pwd));
		this.rememberPassword.setSelected(rememberPassword);

		pack();
		passwordChanged = false;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        message1 = new javax.swing.JLabel();
        message2 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        rememberPassword = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        bOK = new javax.swing.JButton();
        bCancel = new javax.swing.JButton();
        lMessage = new javax.swing.JLabel();

        getContentPane().setLayout(new java.awt.GridBagLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mail Server Password Required");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        message1.setText("Enter your password for citibob");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        getContentPane().add(message1, gridBagConstraints);

        message2.setText("on x.auth.net:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        getContentPane().add(message2, gridBagConstraints);

        password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passwordKeyTyped(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        getContentPane().add(password, gridBagConstraints);

        rememberPassword.setText("Remember this password...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 5);
        getContentPane().add(rememberPassword, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        bOK.setText("OK");
        bOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOKActionPerformed(evt);
            }
        });

        jPanel1.add(bOK);

        bCancel.setText("Cancel");
        bCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelActionPerformed(evt);
            }
        });

        jPanel1.add(bCancel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        lMessage.setForeground(new java.awt.Color(204, 0, 0));
        lMessage.setText("jLabel1");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 11, 0);
        getContentPane().add(lMessage, gridBagConstraints);

        pack();
    }
    // </editor-fold>//GEN-END:initComponents

    private void passwordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordKeyTyped
        // ENTER has same effect as pressing OK
        if (evt.getKeyChar() == '\n') {
            okPressed = true;
            hide();
            return;
        }
        passwordChanged = true;
    }//GEN-LAST:event_passwordKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        okPressed=false;
        hide();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        okPressed=false;
        hide();
    }//GEN-LAST:event_formWindowClosed

    private void bCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelActionPerformed
        okPressed=false;
        hide();
    }//GEN-LAST:event_bCancelActionPerformed

    private void bOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOKActionPerformed
        okPressed=true;
        hide();
    }//GEN-LAST:event_bOKActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
//        new AuthenticatorDialog(new javax.swing.JFrame(), true).show();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancel;
    private javax.swing.JButton bOK;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lMessage;
    private javax.swing.JLabel message1;
    private javax.swing.JLabel message2;
    private javax.swing.JPasswordField password;
    private javax.swing.JCheckBox rememberPassword;
    // End of variables declaration//GEN-END:variables
    
}
