/*
Holyoke Framework: library for GUI-based database applications
This file Copyright (c) 2006-2008 by Robert Fischer

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
/*
 * JKeyedMulti.java
 *
 * Created on April 5, 2008, 8:16 PM
 */

package citibob.swing.typed;

import citibob.jschema.Column;
import citibob.jschema.Schema;
import citibob.jschema.SchemaSet;
import citibob.swing.table.ConstDataGrid;
import citibob.swing.table.DataCols;
import citibob.swing.table.DelegateStyledTM;
import citibob.swing.table.FixedColTableModel;
import citibob.swing.table.StyledTM;
import citibob.swing.table.StyledTM.ButtonAdapter;
import citibob.swing.table.StyledTM.ButtonListener;
import citibob.swing.typed.Swinger.RenderEdit;
import citibob.swing.typed.TypedWidget;
import citibob.swingers.DefaultRenderEdit;
import citibob.swingers.KeyedRenderEdit;
import citibob.swingers.TypedWidgetRenderer;
import citibob.text.KeyedSFormat;
import citibob.text.SFormat;
import citibob.types.JEnum;
import citibob.types.JType;
import citibob.types.JavaJType;
import citibob.types.KeyedModel;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import java.util.Collection;
import java.util.LinkedList;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableColumn;

/**
 NOTE: Unliked most TypedWidgets, this does NOT fire propertyChange("value") events.
 @author  citibob
 */
public class JKeyedMultiPanel extends javax.swing.JPanel
implements KeyedModel.Listener, TypedWidget
{

MyModel tableModel;			// The underlying data in our table
KeyedModel kmodel;
Object segment;
JType valueType;			// Type of value portion of kmodel
Vector vals;				// The values that we can return in our set
//Set selected;					// The set of items selected
boolean[] selected;
//List xtra;					// Extra items we have in our value but cannot display...
protected SFormat kformatter;
List val;					// Value we return overall as a typed widget


	/** Creates new form JKeyedMulti */
	public JKeyedMultiPanel()
	{
		initComponents();
		tableModel = new MyModel();

		DelegateStyledTM stm = new DelegateStyledTM();
		stm.setModels(tableModel, tableModel);

		// Nothing is editable
		stm.setEditableModel(new ConstDataGrid(Boolean.FALSE));

		// Use default rendering
		DataCols<RenderEdit> reCols = new DataCols(
			RenderEdit.class, 2);
		JBoolCheckbox checkbox = new JBoolCheckbox();
		reCols.setColumn(0, new DefaultRenderEdit(
			new TypedWidgetRenderer(checkbox), null));
		stm.setRenderEditModel(reCols);

		// Set up to receive "button" events
		// Respond when the user clicks in either column
		ButtonListener buttonListener = new ButtonAdapter() {
			public boolean onClicked(int row, int col, MouseEvent me) {
				if (me.getButton() != MouseEvent.BUTTON1) return false;
				tableModel.toggleRow(row);
				return true;
			}};
		DataCols<ButtonListener> listenerCols = new DataCols(
			ButtonListener.class, tableModel.getColumnCount());
		listenerCols.setColumn(0, buttonListener);
		listenerCols.setColumn(1, buttonListener);

		stm.setButtonListenerModel(listenerCols);

		table.setStyledTM(stm);
//		table.setSelectionBackground(table.getBackground());

		// Set table column widths
		TableColumn ckCol = table.getColumnModel().getColumn(0);
		int ckWidth = checkbox.getPreferredSize().width;
		ckCol.setMaxWidth(ckWidth);

		// Set up keyboard shortcut
		table.addKeyListener(new KeyAdapter() {
		public void keyTyped(KeyEvent e) {
			if (e.getKeyChar() != ' ') return;
			int row = table.getSelectedRow();
			tableModel.toggleRow(row);
			System.out.println("Space on row " + row);
		}});
		
		
		// Set up the label
		lSelectedCount.setJType(Integer.class, "#");
		lSelectedCount.setValue(0);
	}
	
	/** This method is called from within the constructor to
	 initialize the form.
	 WARNING: Do NOT modify  this code. The content of this method is
	 always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new citibob.swing.StyledTable();
        jPanel1 = new javax.swing.JPanel();
        lSelectStatus = new javax.swing.JLabel();
        lSelectedCount = new citibob.swing.typed.JTypedLabel();

        setLayout(new java.awt.BorderLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        lSelectStatus.setText("Selected: ");
        jPanel1.add(lSelectStatus);

        lSelectedCount.setText("jTypedLabel1");
        jPanel1.add(lSelectedCount);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lSelectStatus;
    private citibob.swing.typed.JTypedLabel lSelectedCount;
    private citibob.swing.StyledTable table;
    // End of variables declaration//GEN-END:variables

	

// --------------------------------------------------------------
/** Convenience method */
public void setKeyedModel(JEnum jenum)
	{ setKeyedModel(jenum.getKeyedModel(), jenum.getSegment()); }
/** Convenience method: sets dropdown equal to the type of the column;
 column must be of type JEnum. */
public void setKeyedModel(Column col)
	{ setKeyedModel((JEnum)col.getType()); }
/** Convenience method: sets dropdown equal to the type of the column.
 Column must be of type JEnum*/
public void setKeyedModel(Schema schema, String colName)
	{ setKeyedModel(schema.getCol(colName)); }
public void setKeyedModel(SchemaSet sset, String schemaName, String colName)
	{ setKeyedModel(sset.get(schemaName), colName); }


public void setKeyedModel(KeyedModel kmodel)
	{ setKeyedModel(kmodel, null); }

public void setKeyedModel(KeyedModel kmodel, Object segment)
{
	table.setRenderEdit(C_VALUE, new KeyedRenderEdit(kmodel));
	if (this.kmodel != null) {
		this.kmodel.removeListener(this);
	}
	this.kmodel = kmodel;
	this.kformatter = new KeyedSFormat(kmodel);
	this.segment = segment;
	kmodel.addListener(this);
	refreshKeyedModel();
}
public void setSegment(Object segment)
{
	this.segment = segment;
	refreshKeyedModel();
}
public void refreshKeyedModel()
{
	Object val = getValue();
//Using JKeyedComboBox.NULL here just causes exceptions if it's actually used.'
	// null here means don't add nulls to our list of options.
	vals = kmodel.newKeyList(segment, null);
	selected = new boolean[vals.size()];
	setValue(val);
	((MyModel)table.getModelU()).fireTableDataChanged();
}
public KeyedModel getKeyedModel()
{ return kmodel; }
// ===========================================================
// TypedWidget
public boolean isInstance(Object obj)
{
	if (obj == null) return kmodel.containsKey(null);
	return obj instanceof Set;
}
public List getValue()
{
	stopEditing();
	return val;
}

/** @param xval Multiple options:<ul>
 * <li>null: Just clear everything</li>
 * <li>Collection: A collection matching (some of) the items in the KeyedModel.</li>
 * <li>Object: Set just one checkbox to true, for which this object matches
 * one item in the KeyedModel</li>
 * </ul>
 */
public void setValue(Object xval)
{
	if (xval == null) {
// TODO: If this is enabled, then the widget gets into a bad state
// when the user sets the "nothing" checkbox.
//		for (int i=0; i < selected.length; ++i) selected[i] = false;
	} else if (xval instanceof Collection) {
		Set set = new TreeSet((Collection)xval);
		int count = 0;
		for (int i=0; i < selected.length; ++i) {
			boolean contains = set.contains(vals.get(i));
			selected[i] = contains;
			if (contains) ++count;
		}
		lSelectedCount.setValue(count);
	} else {
		int count = 0;
		for (int i=0; i < selected.length; ++i) {
			boolean contains = (vals.get(i).equals(xval));
			selected[i] = contains;
			if (contains) ++count;
		}
		lSelectedCount.setValue(count);
	}
	isEditing = true;
}
// --------------------------------------------------------------
// TypedWidget
String colName;
/** Row (if any) in a RowModel we will bind this to at runtime. */
public String getColName() { return colName; }
/** Row (if any) in a RowModel we will bind this to at runtime. */
public void setColName(String col) { colName = col; }

boolean isEditing = false;
/** From TableCellEditor (in case this is being used in a TableCellEditor):
 * Tells the editor to stop editing and accept any partially edited value
 * as the value of the editor. The editor returns false if editing was not
 * stopped; this is useful for editors that validate and can not accept
 * invalid entries. */
public boolean stopEditing() {
	if (!isEditing) return true;

	if (table.getCellEditor() != null) table.getCellEditor().stopCellEditing();
	val = new LinkedList();
//System.out.println("cell editor = " + table.getCellEditor());
//System.out.print("Stop editing: ");
	for (int i=0; i < selected.length; ++i) {
		if (selected[i]) {
			val.add(vals.get(i));
//System.out.print(vals.get(i));
		}
	}
//System.out.println("");
	return true;
}

public Object clone() throws CloneNotSupportedException { return super.clone(); }

// ===========================================================
// KeyedModel.Listener
public void keyedModelChanged()
	{ refreshKeyedModel(); }
// ===========================================================
static final String[] colNames = {"", "Item"};
static final boolean[] editable = {false, false};

static final int C_CHECK = 0;
static final int C_VALUE = 1;


public class MyModel extends FixedColTableModel
{

	public MyModel()
	{
		super(colNames,
			new JType[] {JavaJType.jtBoolean, valueType},
			editable);
	}

	public Object getValueAt(int row, int col)
	{
		switch(col) {
			case C_CHECK : {
				Boolean ret = (selected[row] ? Boolean.TRUE : Boolean.FALSE);
//				System.out.println("value[" + row + "] = " + ret);
				return ret;
			}
			case C_VALUE : return vals.get(row);
		}
		return null;
	}
	public void setValueAt(Object val, int row, int col)
	{
		switch(col) {
			case C_CHECK : {
				boolean oldVal = selected[row];
				boolean newVal = (Boolean)val;
				selected[row] = newVal;
				int count = (Integer)lSelectedCount.getValue();
				if (oldVal && !newVal) {
					lSelectedCount.setValue(count - 1);
				} else if (newVal && !oldVal) {
					lSelectedCount.setValue(count + 1);
				}
//System.out.println("setValueAt(" + row + ") = " + val);
				isEditing = true;
			}
		}
		super.fireTableRowsUpdated(row, row);
	}
	
	void toggleRow(int row) {
		Boolean newVal = selected[row] ? Boolean.FALSE : Boolean.TRUE;
		tableModel.setValueAt(newVal, row, C_CHECK);
	}


	public int getRowCount()
		{ return (vals == null ? 0 : vals.size()); }

}

// ==================================================================
public static void main(String[] args) throws Exception
{
	KeyedModel kmodel = KeyedModel.intKeys("Item 0", "Item 1", "item 2");
	
	JKeyedMultiPanel multi = new JKeyedMultiPanel();
	multi.setKeyedModel(kmodel);
	multi.setValue(1);

	JFrame frame = new JFrame();
	JPanel panel = new JPanel();
	panel.add(multi);
	frame.getContentPane().add(panel);
	frame.pack();
	frame.setVisible(true);

	StyledTM stm = multi.table.getStyledTM();
	System.out.println("Editable 0 = " + stm.isEditable(0,0));
	System.out.println("Editable 1 = " + stm.isEditable(0,1));

}

}
