/*
Holyoke Framework: library for GUI-based database applications
This file Copyright (c) 2006-2008 by Robert Fischer

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/
package citibob.swing.calendar;

import javax.swing.*;
import java.net.URL;
import java.awt.*;

/**
 *
 * @author  citibob
 */
public class JCalendarDateOnly extends javax.swing.JPanel implements JCalendar {
	
	CalModel model;
	
	/** Creates new form JCalendar */
	public JCalendarDateOnly() {
		initComponents();
		URL iconURL = getClass().getResource("images/window-close.png");
		Icon icon = new ImageIcon(iconURL);
		bClose.setIcon(icon);
		bClose.setText(null);
	}

	public void setModel(CalModel m)
	{
		model = m;
		jMonth.setModel(m);
		jYear.setModel(m);
		jDay.setModel(m);
		jDayTF.setModel(m);
		jNull.setCalModel(m);
	}
	
	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jMonth = new citibob.swing.calendar.JMonthChooser();
        jDayTF = new citibob.swing.calendar.JDayTFChooser();
        jYear = new citibob.swing.calendar.JYearChooser();
        bClose = new javax.swing.JButton();
        jNull = new citibob.swing.calendar.JNullChooser();
        jDay = new citibob.swing.calendar.JDayChooser();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        jPanel1.add(jMonth, gridBagConstraints);

        jDayTF.setMinimumSize(new java.awt.Dimension(20, 19));
        jDayTF.setPreferredSize(new java.awt.Dimension(40, 19));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel1.add(jDayTF, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        jPanel1.add(jYear, gridBagConstraints);

        bClose.setText("x");
        bClose.setFocusable(false);
        bClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCloseActionPerformed(evt);
            }
        });

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        jPanel1.add(bClose, gridBagConstraints);

        jNull.setText(null);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jNull, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        add(jDay, java.awt.BorderLayout.CENTER);

    }// </editor-fold>//GEN-END:initComponents

	private void bCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCloseActionPerformed
		model.fireDayButtonSelected();
// TODO add your handling code here:
	}//GEN-LAST:event_bCloseActionPerformed
	
	
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bClose;
    private citibob.swing.calendar.JDayChooser jDay;
    private citibob.swing.calendar.JDayTFChooser jDayTF;
    private citibob.swing.calendar.JMonthChooser jMonth;
    private citibob.swing.calendar.JNullChooser jNull;
    private javax.swing.JPanel jPanel1;
    private citibob.swing.calendar.JYearChooser jYear;
    // End of variables declaration//GEN-END:variables

	
	public static void main(String[] args)
	throws Exception
	{
		JFrame f = new JFrame();
		
		CalModel cm = new CalModel(java.util.TimeZone.getDefault(), true);
		
		JCalendarDateOnly jc = new JCalendarDateOnly();
		jc.setModel(cm);
		f.getContentPane().add(jc);
		
		f.setSize(400,400);
		f.pack();
		f.setVisible(true);
	}
}
